#!/usr/bin/env python3


from tkinter import Tk, Label, Button, Canvas, W, E, N, S, Frame
from tkinter.filedialog import askopenfilename
from tkinter.messagebox import showerror
import time
from Player import  *

class FITSGUI(Frame):
    def __init__(self, master):
        Frame.__init__(self)
        self.master = master
        self.x = 50
        self.y = 40
        self.player = Player()
        #master.title("A simple GUI")

        self.master.title("FiTS Control Console")
        self.master.rowconfigure(5, weight=1)
        self.master.columnconfigure(5, weight=1)
        self.grid(sticky=W+E+N+S)

        self.button = Button(self, text="Browse", command=self.load_file, width=10)
        self.button.grid(row=1, column=0, sticky=W)


        self.label = Label(master, text="FiTS Control Console")
        self.label.grid(row=1, column=0, sticky=E)

        self.greet_button = Button(master, text="Test Button 1", command=self.greet)
        self.greet_button.grid(row=1, column=2, sticky=W)

        self.close_button = Button(master, text="Close", command=master.quit)
        self.close_button.grid(row=2, column=2, sticky=N)
        w = Canvas(master, width=680, height=600)
        w.grid(row=2, column=0, sticky=W)

        w.create_line(0, 0, 200, 100)
        w.create_line(0, 100, 200, 0, fill="red", dash=(4, 4))

        #w.create_rectangle(50, 25, 150, 75, fill="blue") 
        self.w = w   
        self.master.after(0,self.moveDot)

    def greet(self):
        print("Greetings!")
        
    def moveDot(self):
        self.w.create_rectangle(0,0, 680,600 ,fill="grey")
        time.sleep(0.1)
        #print ("FITS:" + str(self.player.playerMap))
        
        if '10000' in self.player.playerMap:
            #self.w.create_rectangle(0,0, 680,600 ,fill="grey")
            playerX = self.player.playerMap['10000'].x*5
            playerY = self.player.playerMap['10000'].y*5
            self.w.create_rectangle(playerX, playerY, playerX+10, playerY+10, fill="blue")
        self.x+=1
        self.master.after(1,self.moveDot)
        
        
    def load_file(self):
        fname = askopenfilename(filetypes=(("Player files", "*.json"),
                                           ("HTML files", "*.html;*.htm"),
                                           ("All files", "*.*") ))
        if fname:
            self.player = Player(fname=fname)
            
            self.player.brainThread.start()
            
#            try:
#                print("""Loading Player: self.settings["template"].set(fname)""")
#                #fp = open(fname,'r')#  
#                p = Player(fname=fname)
#                print (str(p))
#            except:                     # <- naked except is a bad idea
#                showerror("Open Player File", "Failed to read file\n'%s'" % fname)
#            return

root = Tk()
root.quit = root.destroy
fitsGui = FITSGUI(root)
root.mainloop()